#Conexio a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/patitas_al_rescate
spring.datasource.username=postgres
spring.datasource.password=4189

#Driver
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate crea y actualiza tablas automaticamente - usar UPDATE ES PARA QUE CORRIJA POR MI
spring.jpa.hibernate.ddl-auto=validate		

#Mostrar sql en consola
spring.jpa.show-sql=true

#Formatear SQL
spring.jpa.properties.hibernate.format_sql=true

#Logs de Spring
logging.level.org.springframework=INFO

#Logs de Hibernate SQL
logging.level.org.hibernate.SQL=DEBUG

#Mostrar parametros SQL
logging.level.org.hibernate.orm.jdbc.bind=TRACE
